version: 0.2
env:
  variables:
    OS: "amazon_linux_2"
  exported-variables:
    - OS
    - CODEBUILD_BUILD_ID
phases:
  pre_build:
    commands:
      - echo "Installing build prereqs..."
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip && unzip packer.zip -d ./src/pkr
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
      - echo "Executing packer template validation"
      - cd ./src/pkr
      - ./packer validate -var-file="./vars/${OS}.json" ./${OS}.json
  build:
    commands:
      - echo "Executing packer ${OS} build"
      - ./packer build -color=false -var-file="./vars/${OS}.json" ./${OS}.json | tee packer.log
  post_build:
    commands:
      - test -f ${OS}_manifest.json || exit 1
      - AMI_ID=$(cat "${OS}_manifest.json" | jq -r .builds[0].artifact_id |  cut -d':' -f2)
      - aws ssm put-parameter --name "/ami/${OS}/id" --value $AMI_ID --type String --overwrite
      - echo "${OS} build completed on $(date)"v